/**
 * POST /api/bazi
 *
 * Computes a BaZi (Four Pillars, 四柱八字) chart from a Solar birth
 * datetime and returns a JSON structure the client renders.
 *
 * Body:
 *   {
 *     year, month, day, hour, minute,   // Solar (Gregorian) calendar
 *     gender,                            // "male" | "female"
 *     lang                               // "zh" | "en"
 *   }
 *
 * Engine: `lunar-typescript` (zero deps, authoritative sexagenary
 * calendar). Runs on Node runtime (Fluid Compute default) — Edge would
 * work too, but the library is ~250KB and Node keeps debugging simple.
 *
 * The detailed AI reading is a separate call to /api/ai-reading with
 * sku "bazi-basic" ($2.99) or "bazi-full" ($4.99); this endpoint only
 * does deterministic chart computation so it is free.
 */

const { Solar } = require('lunar-typescript');

// Five-element stats across 8 natal positions (gan + zhi) + 藏干.
// Matches the Chinese convention: 本气 counts full weight; 藏干 counts
// partial. We use a simple "all counted equally" tally — detail weight
// can be added later if the AI prompt needs it.
const GAN_WU_XING = {
  '甲': '木', '乙': '木',
  '丙': '火', '丁': '火',
  '戊': '土', '己': '土',
  '庚': '金', '辛': '金',
  '壬': '水', '癸': '水',
};
const ZHI_WU_XING = {
  '子': '水', '丑': '土', '寅': '木', '卯': '木',
  '辰': '土', '巳': '火', '午': '火', '未': '土',
  '申': '金', '酉': '金', '戌': '土', '亥': '水',
};
const WU_XING_EN = { '金': 'Metal', '木': 'Wood', '水': 'Water', '火': 'Fire', '土': 'Earth' };

function countWuXing(eightChar) {
  const counts = { '金': 0, '木': 0, '水': 0, '火': 0, '土': 0 };
  const gans = [eightChar.getYearGan(), eightChar.getMonthGan(), eightChar.getDayGan(), eightChar.getTimeGan()];
  const zhis = [eightChar.getYearZhi(), eightChar.getMonthZhi(), eightChar.getDayZhi(), eightChar.getTimeZhi()];
  gans.forEach((g) => { counts[GAN_WU_XING[g]] += 1; });
  zhis.forEach((z) => { counts[ZHI_WU_XING[z]] += 1; });
  return counts;
}

// Very simplified 日主 strength heuristic: count same-element and
// generating-element score across 8 positions. Classical analysis is
// far richer (月令 weighting, 通根, 透干 etc.) — kept coarse here so the
// free-tier label is a hint, not a verdict. AI reading refines this.
const GENERATE = { '木': '水', '火': '木', '土': '火', '金': '土', '水': '金' }; // X is generated by GENERATE[X]
function estimateStrength(dayGan, counts) {
  const self = GAN_WU_XING[dayGan];
  const supporter = GENERATE[self];
  const score = counts[self] * 2 + counts[supporter];
  if (score >= 6) return 'strong';
  if (score >= 4) return 'balanced';
  return 'weak';
}

function buildChart(body) {
  const { year, month, day, hour, minute, gender, lang } = body;
  const solar = Solar.fromYmdHms(
    Number(year), Number(month), Number(day),
    Number(hour) || 0, Number(minute) || 0, 0
  );
  const lunar = solar.getLunar();
  const eight = lunar.getEightChar();

  // gender: 1 = male, 0 = female for Yun calc.
  const genderFlag = gender === 'female' ? 0 : 1;
  const yun = eight.getYun(genderFlag);
  const daYunRaw = yun.getDaYun();

  const pillars = ['Year', 'Month', 'Day', 'Time'].map((label, i) => {
    const gan = [eight.getYearGan(), eight.getMonthGan(), eight.getDayGan(), eight.getTimeGan()][i];
    const zhi = [eight.getYearZhi(), eight.getMonthZhi(), eight.getDayZhi(), eight.getTimeZhi()][i];
    const hideGan = [eight.getYearHideGan(), eight.getMonthHideGan(), eight.getDayHideGan(), eight.getTimeHideGan()][i];
    const naYin = [eight.getYearNaYin(), eight.getMonthNaYin(), eight.getDayNaYin(), eight.getTimeNaYin()][i];
    const shiShenGan = [eight.getYearShiShenGan(), eight.getMonthShiShenGan(), 'self', eight.getTimeShiShenGan()][i];
    const shiShenZhi = [eight.getYearShiShenZhi(), eight.getMonthShiShenZhi(), eight.getDayShiShenZhi(), eight.getTimeShiShenZhi()][i];
    return {
      label,
      gan, zhi,
      ganWuXing: GAN_WU_XING[gan],
      zhiWuXing: ZHI_WU_XING[zhi],
      ganWuXingEn: WU_XING_EN[GAN_WU_XING[gan]],
      zhiWuXingEn: WU_XING_EN[ZHI_WU_XING[zhi]],
      hideGan,
      naYin,
      shiShenGan,
      shiShenZhi,
    };
  });

  const counts = countWuXing(eight);
  const dayGan = eight.getDayGan();
  const strength = estimateStrength(dayGan, counts);

  const daYun = daYunRaw.slice(0, 8).map((d) => ({
    startAge: d.getStartAge(),
    startYear: d.getStartYear(),
    ganZhi: d.getGanZhi(),
  })).filter((d) => d.ganZhi); // drop the pre-start empty slot

  return {
    input: {
      solar: { year: solar.getYear(), month: solar.getMonth(), day: solar.getDay(), hour: solar.getHour(), minute: solar.getMinute() },
      lunar: lunar.toString(),
      gender: genderFlag === 1 ? 'male' : 'female',
      lang,
    },
    pillars,
    dayMaster: {
      gan: dayGan,
      wuXing: GAN_WU_XING[dayGan],
      wuXingEn: WU_XING_EN[GAN_WU_XING[dayGan]],
      strength,
    },
    wuXingCounts: counts,
    yun: {
      startYear: yun.getStartYear(),
      startMonth: yun.getStartMonth(),
      startDay: yun.getStartDay(),
      daYun,
    },
  };
}

module.exports = async function handler(req, res) {
  if (req.method !== 'POST') {
    res.status(405).json({ error: 'Method not allowed' });
    return;
  }

  const body = req.body || {};
  const { year, month, day } = body;
  if (!year || !month || !day) {
    res.status(400).json({ error: 'year, month, day required' });
    return;
  }

  try {
    const chart = buildChart(body);
    res.status(200).json(chart);
  } catch (err) {
    console.error('BaZi compute failed:', err.message);
    res.status(500).json({ error: 'Failed to compute chart' });
  }
};
